// protoc generate parameter
// clang-format off
// 
// =========================
#include "struct_pb/struct_pb.hpp"
// Generated by the protocol buffer compiler (struct_pb).  DO NOT EDIT!
// source: test_large_enum_value.proto

#pragma once

#include <limits>
#include <string>
#include <type_traits>
#include <memory>
#include <map>
#include <variant>
#include <vector>
#include <optional>

namespace protobuf_unittest {
struct TestLargeEnumValue;
struct TestLargeEnumValue {
  enum class EnumWithLargeValue: int {
    VALUE_1 = 1,
    VALUE_MAX = 2147483647,
  };
};

} // namespace protobuf_unittest
namespace struct_pb {
namespace internal {
// ::protobuf_unittest::TestLargeEnumValue
std::size_t get_needed_size(const ::protobuf_unittest::TestLargeEnumValue&, const ::struct_pb::UnknownFields& unknown_fields = {});
void serialize_to(char*, std::size_t, const ::protobuf_unittest::TestLargeEnumValue&, const ::struct_pb::UnknownFields& unknown_fields = {});
bool deserialize_to(::protobuf_unittest::TestLargeEnumValue&, const char*, std::size_t, ::struct_pb::UnknownFields& unknown_fields);
bool deserialize_to(::protobuf_unittest::TestLargeEnumValue&, const char*, std::size_t);

} // internal
} // struct_pb
// clang-format on
