check_library_exists(ibverbs ibv_create_qp "" HAVE_IBVERBS_IBV)
if(HAVE_IBVERBS_IBV)
  set(IBVERBS_LIBRARY ibverbs)
  add_compile_definitions("YLT_IBVERBS")
  message(STATUS "have libibverbs")
endif()