file(GLOB children src/*)
foreach(child ${children})
  if(BUILD_UNIT_TESTS AND EXISTS ${child}/examples)
    add_subdirectory(${child}/examples)
  endif()
  if(BUILD_BENCHMARK AND EXISTS ${child}/tests)
    add_subdirectory(${child}/tests)
  endif()
  if(BUILD_EXAMPLES AND EXISTS ${child}/benchmark)
    add_subdirectory(${child}/benchmark)
  endif()
endforeach()
add_subdirectory(src/struct_pb)